version: "3"
services:
  nginx:
    container_name: nginx
    build: ./nginx    #Dockerfileに任せる
    ports:
      - "9000:80"   #9000を80にポートマッピング http://localhost:9000 で動く。
    volumes:
        - ./data/www/my-test/dist:/var/www/html  # 「html」のディレクトリ内容をlinux?上のそこにマウントするので、「html」配下が即時反映される仕組み。

  vue:
    container_name: vue
    build: ./vue
    # ports:
    #   - "9000:9000"
    volumes:
      - ./data/www:/app
    tty: true
